export const currencyData = {
  "en": { symbol: "₹", amount: "1000", name: "Indian Rupee" },
  "hi": { symbol: "₹", amount: "1000", name: "भारतीय रुपया" },
  "bn": { symbol: "৳", amount: "১৩৩৪", name: "বাংলাদেশী টাকা" },
  "ur": { symbol: "₨", amount: "3129", name: "پاکستانی روپیہ" },
  "ru": { symbol: "₽", amount: "858.26", name: "Российский рубль" },
  "pt": { symbol: "R$", amount: "60.47", name: "Real brasileiro" },
  "es": { symbol: "€", amount: "9.57", name: "Euro" },
  "fr": { symbol: "€", amount: "9.57", name: "Euro" },
  "de": { symbol: "€", amount: "9.57", name: "Euro" },
  "it": { symbol: "€", amount: "9.57", name: "Euro" },
  "ph": { symbol: "₱", amount: "645", name: "Philippine Peso" },
  "vi": { symbol: "₫", amount: "298000", name: "Vietnamese Dong" },
  "tr": { symbol: "₺", amount: "347", name: "Turkish Lira" },
  "ar": { symbol: "﷼", amount: "41.7", name: "Saudi Riyal" },
  "fa": { symbol: "﷼", amount: "510000", name: "Iranian Rial" },
  "zh": { symbol: "¥", amount: "90.05", name: "Chinese Yuan" },
  "ja": { symbol: "¥", amount: "1710", name: "Japanese Yen" },
  "ko": { symbol: "₩", amount: "14840", name: "South Korean Won" },
  "uk": { symbol: "₴", amount: "460", name: "Ukrainian Hryvnia" },
  "pt-pt": { symbol: "€", amount: "9.57", name: "Euro" },
  "en-ng": { symbol: "₦", amount: "10250", name: "Nigerian Naira" },
  "ms": { symbol: "RM", amount: "54.2", name: "Malaysian Ringgit" },
  "he": { symbol: "₪", amount: "40.32", name: "Israeli Shekel" },
  "th": { symbol: "฿", amount: "410", name: "Thai Baht" },
  "id": { symbol: "Rp", amount: "184500", name: "Indonesian Rupiah" },
  "si": { symbol: "Rs", amount: "4000", name: "Sri Lankan Rupee" },
  "ne": { symbol: "Rs", amount: "1600", name: "Nepalese Rupee" },
  "ps": { symbol: "؋", amount: "865", name: "Afghan Afghani" },
  "uz": { symbol: "soʻm", amount: "135500", name: "Uzbekistani Som" },
  "kk": { symbol: "₸", amount: "5400", name: "Kazakhstani Tenge" },
  "tg": { symbol: "ЅМ", amount: "119", name: "Tajikistani Somoni" },
  "el": { symbol: "€", amount: "9.57", name: "Euro" },
  "pl": { symbol: "zł", amount: "41", name: "Polish Zloty" },
  "nl": { symbol: "€", amount: "9.57", name: "Euro" },
  "ro": { symbol: "lei", amount: "48", name: "Romanian Leu" },
  "bg": { symbol: "лв", amount: "18", name: "Bulgarian Lev" },
  "cs": { symbol: "Kč", amount: "218", name: "Czech Koruna" },
  "sk": { symbol: "€", amount: "9.57", name: "Euro" },
  "hu": { symbol: "Ft", amount: "4400", name: "Hungarian Forint" },
  "sr": { symbol: "дин", amount: "1310", name: "Serbian Dinar" }
};
