// currencies.js - Complete and Fixed
export const currencyData = {
  "en": { symbol: "₹", amount: "1000", name: "Indian Rupee" },
  "hi": { symbol: "₹", amount: "1000", name: "Indian Rupee" },
  "bn": { symbol: "৳", amount: "1330", name: "Bangladeshi Taka" },
  "ur": { symbol: "₨", amount: "3080", name: "Pakistani Rupee" },
  "ru": { symbol: "₽", amount: "850", name: "Russian Ruble" },
  "pt": { symbol: "R$", amount: "57", name: "Brazilian Real" },
  "es": { symbol: "€", amount: "11", name: "Euro" },
  "fr": { symbol: "€", amount: "11", name: "Euro" },
  "de": { symbol: "€", amount: "11", name: "Euro" },
  "it": { symbol: "€", amount: "11", name: "Euro" },
  "ar": { symbol: "﷼", amount: "45", name: "Saudi Riyal" },
  "zh": { symbol: "¥", amount: "86", name: "Chinese Yuan" },
  "ja": { symbol: "¥", amount: "1650", name: "Japanese Yen" },
  "ko": { symbol: "₩", amount: "14500", name: "South Korean Won" },
  "fil": { symbol: "₱", amount: "670", name: "Philippine Peso" },
  "vi": { symbol: "₫", amount: "295000", name: "Vietnamese Dong" },
  "tr": { symbol: "₺", amount: "380", name: "Turkish Lira" },
  "fa": { symbol: "﷼", amount: "500000", name: "Iranian Rial" },
  "uk": { symbol: "₴", amount: "450", name: "Ukrainian Hryvnia" },
  "pt-pt": { symbol: "€", amount: "11", name: "Euro" },
  "en-ng": { symbol: "₦", amount: "16500", name: "Nigerian Naira" },
  "ms": { symbol: "RM", amount: "56", name: "Malaysian Ringgit" },
  "he": { symbol: "₪", amount: "45", name: "Israeli Shekel" },
  "th": { symbol: "฿", amount: "430", name: "Thai Baht" },
  "id": { symbol: "Rp", amount: "185000", name: "Indonesian Rupiah" },
  "si": { symbol: "රු", amount: "3600", name: "Sri Lankan Rupee" },
  "ne": { symbol: "रू", amount: "1600", name: "Nepalese Rupee" },
  "ps": { symbol: "؋", amount: "860", name: "Afghan Afghani" },
  "uz": { symbol: "so'm", amount: "135000", name: "Uzbekistani Som" },
  "kk": { symbol: "₸", amount: "5200", name: "Kazakhstani Tenge" },
  "tg": { symbol: "ЅМ", amount: "135", name: "Tajikistani Somoni" },
  "el": { symbol: "€", amount: "11", name: "Euro" },
  "pl": { symbol: "zł", amount: "50", name: "Polish Zloty" },
  "nl": { symbol: "€", amount: "11", name: "Euro" },
  "ro": { symbol: "lei", amount: "55", name: "Romanian Leu" },
  "bg": { symbol: "лв", amount: "22", name: "Bulgarian Lev" },
  "cs": { symbol: "Kč", amount: "280", name: "Czech Koruna" },
  "sk": { symbol: "€", amount: "11", name: "Euro" },
  "hu": { symbol: "Ft", amount: "4000", name: "Hungarian Forint" },
  "sr": { symbol: "дин", amount: "1100", name: "Serbian Dinar" }
};
